import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" type="image/png" />
      </head>
      <body
        className={`antialiased`}
        style={{ fontFamily: "var(--font-boring-sans)" }}
      >
        {children}
      </body>
    </html>
  );
}
